// Automatic FlutterFlow imports
import '/backend/supabase/supabase.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'dart:async';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// a-Paw icon pack (Crafted Pixel) and the a-Paw design kit. GENERATED by
/// tool/build_icons.py in the care-a-paw repository; do not edit by hand.
///
///   apawIcon('care-health-vaccination', color: ..., size: 24)
///   apawEmpty('care-empty-no-pets', width: 200)
///   apawLogo('care', size: 64), apawHeader(...), apawPrimary(...), ApawFrontDoor(...)
///
/// FeedIcons itself is a holder and is not placed on a page.
class FeedIcons extends StatelessWidget {
  const FeedIcons({super.key, this.width, this.height});

  final double? width;
  final double? height;

  @override
  Widget build(BuildContext context) =>
      apawIcon('feed-about-cooking-drum-filled', size: width ?? 24, color: const Color(0xFF1F5148));
}

// ====================================================================
// a-Paw design kit. GENERATED from tool/apaw_kit.py (care-a-paw repo);
// identical in every a-Paw app. Do not edit by hand.
// ====================================================================

class ApawColors {
  static const forest = Color(0xFF1F5148);
  static const forestSoft = Color(0xFF2B6356);
  static const ink = Color(0xFF23332F);
  static const muted = Color(0xFF55625D);
  static const orange = Color(0xFFFF7900);
  static const ivory = Color(0xFFF6F1E7);
  static const cream = Color(0xFFFFFCF7);
  static const sand = Color(0xFFE6DFD1);
  static const mint = Color(0xFFDDEBE3);
  static const peach = Color(0xFFFFEEDD);
  static const lost = Color(0xFFB3261E);
  static const found = Color(0xFF2E7D32);
}

const _apForest = ApawColors.forest;
const _apOrange = ApawColors.orange;
const _apIvory = ApawColors.ivory;
const _apMuted = ApawColors.muted;
const _apLine = ApawColors.sand;

/// Heading type (Fraunces).
TextStyle apawDisplay({double size = 28, Color color = ApawColors.forest, FontWeight weight = FontWeight.w700}) =>
    GoogleFonts.fraunces(fontSize: size, fontWeight: weight, color: color, height: 1.15);

/// Body type (Figtree).
TextStyle apawText({double size = 15, Color color = ApawColors.ink, FontWeight weight = FontWeight.w500, double height = 1.4}) =>
    GoogleFonts.figtree(fontSize: size, fontWeight: weight, color: color, height: height);

/// The one a-Paw look: light, forest text, white fields, orange buttons.
/// Every screen is wrapped in it, so the phone's dark mode can't change it.
ThemeData apawTheme() {
  final scheme = ColorScheme.fromSeed(seedColor: _apForest, brightness: Brightness.light).copyWith(
    primary: _apForest,
    onPrimary: Colors.white,
    secondary: _apOrange,
    onSecondary: _apForest,
    surface: Colors.white,
    onSurface: _apForest,
    onSurfaceVariant: _apMuted,
    outline: _apLine,
  );
  final base = ThemeData(useMaterial3: true, brightness: Brightness.light, colorScheme: scheme);
  final shape14 = RoundedRectangleBorder(borderRadius: BorderRadius.circular(14));
  return base.copyWith(
    scaffoldBackgroundColor: _apIvory,
    canvasColor: _apIvory,
    textTheme: GoogleFonts.figtreeTextTheme(base.textTheme).apply(bodyColor: ApawColors.ink, displayColor: _apForest),
    iconTheme: const IconThemeData(color: _apForest),
    listTileTheme: const ListTileThemeData(textColor: _apForest, iconColor: _apForest),
    appBarTheme: AppBarTheme(
        backgroundColor: Colors.transparent,
        foregroundColor: _apForest,
        elevation: 0,
        scrolledUnderElevation: 0,
        surfaceTintColor: Colors.transparent,
        centerTitle: false,
        titleTextStyle: apawDisplay(size: 22)),
    dialogTheme: DialogThemeData(
        backgroundColor: ApawColors.cream,
        surfaceTintColor: Colors.transparent,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(22)),
        titleTextStyle: apawDisplay(size: 22)),
    bottomSheetTheme: const BottomSheetThemeData(
        backgroundColor: _apIvory,
        surfaceTintColor: Colors.transparent,
        showDragHandle: true,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(24)))),
    filledButtonTheme: FilledButtonThemeData(
      style: FilledButton.styleFrom(
        backgroundColor: _apOrange,
        foregroundColor: _apForest,
        disabledBackgroundColor: const Color(0x66FF7900),
        disabledForegroundColor: const Color(0x991F5148),
        minimumSize: const Size(64, 50),
        shape: shape14,
        textStyle: GoogleFonts.figtree(fontSize: 16, fontWeight: FontWeight.w800),
      ),
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        backgroundColor: _apOrange,
        foregroundColor: _apForest,
        elevation: 0,
        minimumSize: const Size(64, 50),
        shape: shape14,
        textStyle: GoogleFonts.figtree(fontSize: 16, fontWeight: FontWeight.w800),
      ),
    ),
    outlinedButtonTheme: OutlinedButtonThemeData(
      style: OutlinedButton.styleFrom(
        foregroundColor: _apForest,
        backgroundColor: Colors.white,
        side: const BorderSide(color: _apLine, width: 1.4),
        minimumSize: const Size(64, 48),
        shape: shape14,
        textStyle: GoogleFonts.figtree(fontSize: 15.5, fontWeight: FontWeight.w700),
      ),
    ),
    textButtonTheme: TextButtonThemeData(
      style: TextButton.styleFrom(
        foregroundColor: _apForest,
        minimumSize: const Size(44, 44),
        textStyle: GoogleFonts.figtree(fontSize: 15, fontWeight: FontWeight.w700),
      ),
    ),
    floatingActionButtonTheme: FloatingActionButtonThemeData(
      backgroundColor: _apOrange,
      foregroundColor: _apForest,
      elevation: 2,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(18)),
      extendedTextStyle: GoogleFonts.figtree(fontSize: 15.5, fontWeight: FontWeight.w800),
    ),
    navigationBarTheme: NavigationBarThemeData(
      backgroundColor: Colors.white,
      surfaceTintColor: Colors.transparent,
      indicatorColor: ApawColors.mint,
      height: 68,
      labelTextStyle: WidgetStateProperty.resolveWith((s) => GoogleFonts.figtree(
          fontSize: 12.5,
          fontWeight: s.contains(WidgetState.selected) ? FontWeight.w800 : FontWeight.w600,
          color: s.contains(WidgetState.selected) ? _apForest : _apMuted)),
    ),
    snackBarTheme: SnackBarThemeData(
      backgroundColor: _apForest,
      contentTextStyle: GoogleFonts.figtree(color: Colors.white, fontSize: 14.5, fontWeight: FontWeight.w600),
      behavior: SnackBarBehavior.floating,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
    ),
    progressIndicatorTheme: const ProgressIndicatorThemeData(color: _apOrange),
    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: Colors.white,
      labelStyle: const TextStyle(color: _apMuted),
      floatingLabelStyle: const TextStyle(color: _apForest, fontWeight: FontWeight.w600),
      hintStyle: const TextStyle(color: _apMuted),
      counterStyle: const TextStyle(color: _apMuted),
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(14), borderSide: const BorderSide(color: _apLine)),
      enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(14), borderSide: const BorderSide(color: _apLine)),
      focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(14), borderSide: const BorderSide(color: _apForest, width: 1.6)),
    ),
    textSelectionTheme: const TextSelectionThemeData(
        cursorColor: _apForest, selectionColor: Color(0x331F5148), selectionHandleColor: _apForest),
    chipTheme: ChipThemeData(
      backgroundColor: Colors.white,
      selectedColor: _apForest,
      disabledColor: _apLine,
      labelStyle: GoogleFonts.figtree(color: _apForest, fontWeight: FontWeight.w700),
      secondaryLabelStyle: GoogleFonts.figtree(color: Colors.white, fontWeight: FontWeight.w700),
      checkmarkColor: Colors.white,
      side: const BorderSide(color: _apLine),
      shape: const StadiumBorder(),
    ),
    segmentedButtonTheme: SegmentedButtonThemeData(
      style: ButtonStyle(
        backgroundColor: WidgetStateProperty.resolveWith((s) => s.contains(WidgetState.selected) ? _apForest : Colors.white),
        foregroundColor: WidgetStateProperty.resolveWith((s) => s.contains(WidgetState.selected) ? Colors.white : _apForest),
        side: WidgetStateProperty.all(const BorderSide(color: _apLine)),
      ),
    ),
    switchTheme: SwitchThemeData(
      thumbColor: WidgetStateProperty.resolveWith((s) => s.contains(WidgetState.selected) ? Colors.white : _apMuted),
      trackColor: WidgetStateProperty.resolveWith((s) => s.contains(WidgetState.selected) ? _apForest : _apLine),
      trackOutlineColor: WidgetStateProperty.all(Colors.transparent),
    ),
    checkboxTheme: CheckboxThemeData(
      fillColor: WidgetStateProperty.resolveWith((s) => s.contains(WidgetState.selected) ? _apForest : Colors.white),
      checkColor: WidgetStateProperty.all(Colors.white),
      side: const BorderSide(color: _apMuted, width: 1.5),
    ),
    dividerTheme: const DividerThemeData(color: _apLine),
  );
}

/// Wraps [child] in the a-Paw theme.
Widget apawThemed(Widget child) => Theme(data: apawTheme(), child: child);

/// A pack icon, tinted [color]. Unknown names draw nothing (never crash).
Widget apawIcon(String name, {double size = 24, Color color = ApawColors.ink}) {
  final svg = _apawUi[name];
  if (svg == null) return SizedBox(width: size, height: size);
  return SvgPicture.string(svg,
      width: size, height: size, colorFilter: ColorFilter.mode(color, BlendMode.srcIn), excludeFromSemantics: true);
}

/// An empty-state picture (240 x 160 artwork) at [width].
Widget apawEmpty(String name, {double width = 200}) {
  Widget plain() {
    final svg = _apawEmpty[name];
    if (svg == null) return SizedBox(width: width, height: width * 2 / 3);
    return SvgPicture.string(svg, width: width, height: width * 2 / 3, excludeFromSemantics: true);
  }

  return ValueListenableBuilder<String>(
    valueListenable: ApawSkin.current,
    builder: (_, skin, __) => skin == 'standard'
        ? plain()
        : SvgPicture.network(ApawSkin.art(skin, 'empty-states', name),
            width: width, height: width * 2 / 3, excludeFromSemantics: true, placeholderBuilder: (_) => plain()),
  );
}

/// An app's logo mark ('care', 'track', 'snap', 'feed', 'adopt', 'mind').
Widget apawLogo(String app, {double size = 64}) {
  Widget plain() {
    final svg = _apawLogos[app];
    return svg == null
        ? Container(width: size, height: size, color: ApawColors.forest)
        : SvgPicture.string(svg, width: size, height: size, excludeFromSemantics: true);
  }

  return ClipRRect(
    borderRadius: BorderRadius.circular(size * 0.24),
    child: ValueListenableBuilder<String>(
      valueListenable: ApawSkin.current,
      builder: (_, skin, __) => skin == 'standard'
          ? plain()
          : SvgPicture.network('${ApawSkin.packBase}/${ApawSkin.folder(skin)}/app-icons/$app/$app-app-master.svg',
              width: size, height: size, excludeFromSemantics: true, placeholderBuilder: (_) => plain()),
    ),
  );
}

/// "Look & feel": the same seven skins as Spot a Paw. A skin changes the
/// scenery behind the pages, never the buttons, icons or text colours. The
/// choice is saved on the phone and on the a-Paw account (profiles.skin), so
/// it follows the person into every a-Paw app.
class ApawSkin {
  // Spot a Paw's skin art (same folders and names as Spot uses).
  static const base = 'https://qyyydmjrrtyauyawheos.supabase.co/storage/v1/object/public/'
      'report-media/ea87c808-aa49-4286-829b-e69250be5b84/icons';
  static const skins = <(String, String, String)>[
    ('standard', 'No Frills', 'Flat and plain, easy on the eyes'),
    ('eg', 'Egyptian', 'Papyrus scrolls, Nile scenes'),
    ('south-asia', 'South Asia', 'Fibre paper, rivers and rice fields'),
    ('southeast-asia', 'Southeast Asia', 'Mulberry paper, bamboo and terraces'),
    ('west-asia', 'West Asia', 'Parchment, palms and stone courtyards'),
    ('south-america', 'South America', 'Woven paper, rivers and highlands'),
    ('africa', 'Africa', 'Earth pigments, savannah light and woven cloth'),
  ];
  static final current = ValueNotifier<String>('standard');
  static bool _loaded = false;

  static String label(String key) =>
      skins.firstWhere((s) => s.$1 == key, orElse: () => skins.first).$2;

  // Only scenes light enough for dark text in every region (measured
  // 30 Sep: profile, auth, dusk, spot and communities are too dark in some).
  static const _lightScenes = {'paws', 'onboarding', 'rescues'};
  static String bg(String skin, String scene) =>
      '$base/$skin/bg_${_lightScenes.contains(scene) ? scene : 'paws'}.jpg';

  /// The a-Paw regional pack (a-paw-seven-skins, Crafted Pixel), published
  /// with the web previews: badges, empty states and app logos per region.
  static const packBase = 'https://spotapaw.github.io/a-paw-apps/skins';
  static String folder(String skin) => skin == 'eg' ? 'egyptian' : skin;

  /// A regional file for a pack name like 'care-health-vaccination'
  /// (kind: 'badges' or 'empty-states'; the app folder is the name's prefix).
  static String art(String skin, String kind, String name) =>
      '$packBase/${folder(skin)}/$kind/${name.split('-').first}/$name.svg';

  /// Each region's paper colour (theme.json), used lightly on cards.
  static const paper = <String, Color>{
    'eg': Color(0xFFF3E5BC),
    'south-asia': Color(0xFFF2DDD0),
    'southeast-asia': Color(0xFFE3EAD3),
    'west-asia': Color(0xFFF0DEC8),
    'south-america': Color(0xFFECE8D6),
    'africa': Color(0xFFEAD6B5),
  };

  static String _norm(String s) => s == 'egypt' || s == 'egyptian' ? 'eg' : s;

  /// Phone first (instant), then the account (follows the person).
  static Future<void> load() async {
    if (_loaded) return;
    _loaded = true;
    try {
      final prefs = await SharedPreferences.getInstance();
      final s = prefs.getString('apaw_skin');
      if (s != null && s.isNotEmpty) current.value = _norm(s);
    } catch (_) {}
    try {
      final uid = SupaFlow.client.auth.currentUser?.id;
      if (uid == null) return;
      final r = await SupaFlow.client.from('profiles').select('skin').eq('id', uid).maybeSingle();
      final s = _norm((r?['skin'] ?? '').toString());
      if (s == 'standard' && current.value != 'standard') {
        // Picked on this phone before the account could store it: keep it.
        await SupaFlow.client.from('profiles').update({'skin': current.value}).eq('id', uid);
      } else if (s.isNotEmpty && skins.any((k) => k.$1 == s) && s != current.value) {
        current.value = s;
        (await SharedPreferences.getInstance()).setString('apaw_skin', s);
      }
    } catch (_) {}
  }

  static Future<void> set(String s) async {
    current.value = s;
    try {
      (await SharedPreferences.getInstance()).setString('apaw_skin', s);
    } catch (_) {}
    try {
      final uid = SupaFlow.client.auth.currentUser?.id;
      if (uid != null) await SupaFlow.client.from('profiles').update({'skin': s}).eq('id', uid);
    } catch (_) {}
  }
}

/// The page background every a-Paw screen sits on: the chosen skin's
/// scenery under a soft ivory wash (text stays forest and readable), or the
/// plain warm ivory for No Frills. [scene] picks the picture: spot, paws,
/// profile, dusk, rescues, onboarding, auth, communities.
class ApawBackground extends StatefulWidget {
  const ApawBackground({super.key, required this.child, this.scene = 'spot'});
  final Widget child;
  final String scene;

  @override
  State<ApawBackground> createState() => _ApawBackgroundState();
}

class _ApawBackgroundState extends State<ApawBackground> {
  @override
  void initState() {
    super.initState();
    ApawSkin.load();
  }

  @override
  Widget build(BuildContext context) => ValueListenableBuilder<String>(
        valueListenable: ApawSkin.current,
        builder: (context, skin, _) {
          if (skin == 'standard') {
            return DecoratedBox(
              decoration: const BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [Color(0xFFFBF7EF), ApawColors.ivory, Color(0xFFF1E6D3)],
                  stops: [0, .55, 1],
                ),
              ),
              child: widget.child,
            );
          }
          return Stack(fit: StackFit.expand, children: [
            const ColoredBox(color: ApawColors.ivory),
            Image.network(
              ApawSkin.bg(skin, widget.scene),
              fit: BoxFit.cover,
              alignment: Alignment.center,
              gaplessPlayback: true,
              errorBuilder: (_, __, ___) => const SizedBox.shrink(),
            ),
            const DecoratedBox(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [Color(0xE6F6F1E7), Color(0xA6F6F1E7), Color(0x99F6F1E7), Color(0xD9F6F1E7)],
                  stops: [0, .22, .6, 1],
                ),
              ),
            ),
            widget.child,
          ]);
        },
      );
}

Widget apawBackground({required Widget child, String scene = 'spot'}) =>
    ApawBackground(scene: scene, child: child);

/// "Look & feel" picker: the seven skins with a preview of each.
Future<void> showApawSkinPicker(BuildContext context) async {
  await ApawSkin.load();
  if (!context.mounted) return;
  await showModalBottomSheet<void>(
    context: context,
    isScrollControlled: true,
    builder: (sheet) => apawThemed(ConstrainedBox(
      constraints: BoxConstraints(maxHeight: MediaQuery.of(sheet).size.height * .85),
      child: ValueListenableBuilder<String>(
        valueListenable: ApawSkin.current,
        builder: (_, cur, __) => ListView(shrinkWrap: true, padding: const EdgeInsets.fromLTRB(20, 0, 20, 24), children: [
          Text('Look & feel', style: apawDisplay(size: 26)),
          const SizedBox(height: 4),
          Text('Scenery from around the world behind your pages. Buttons stay the same. Works in every a-Paw app.',
              style: apawText(color: ApawColors.muted)),
          const SizedBox(height: 14),
          for (final s in ApawSkin.skins)
            Padding(
              padding: const EdgeInsets.only(bottom: 10),
              child: apawCard(
                color: s.$1 == cur ? const Color(0xFFFFF4E8) : ApawColors.cream,
                onTap: () => ApawSkin.set(s.$1),
                padding: const EdgeInsets.all(10),
                child: Row(children: [
                  ClipRRect(
                    borderRadius: BorderRadius.circular(10),
                    child: SizedBox(
                      width: 52,
                      height: 72,
                      child: s.$1 == 'standard'
                          ? const DecoratedBox(
                              decoration: BoxDecoration(
                                  gradient: LinearGradient(
                                      begin: Alignment.topCenter,
                                      end: Alignment.bottomCenter,
                                      colors: [Color(0xFFFBF7EF), Color(0xFFF1E6D3)])))
                          : Image.network(ApawSkin.bg(s.$1, 'onboarding'), fit: BoxFit.cover,
                              errorBuilder: (_, __, ___) => const ColoredBox(color: ApawColors.sand)),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                      Text(s.$2, style: apawText(size: 16, color: ApawColors.forest, weight: FontWeight.w800)),
                      Text(s.$3, style: apawText(size: 13, color: ApawColors.muted)),
                    ]),
                  ),
                  Container(
                    width: 22,
                    height: 22,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: s.$1 == cur ? ApawColors.orange : Colors.white,
                      border: Border.all(color: s.$1 == cur ? ApawColors.orange : ApawColors.muted, width: 2),
                    ),
                    child: s.$1 == cur ? const Icon(Icons.check_rounded, size: 14, color: ApawColors.forest) : null,
                  ),
                ]),
              ),
            ),
        ]),
      ),
    )),
  );
}

/// The "Look & feel" row for an Account screen.
Widget apawSkinRow(BuildContext context) => ValueListenableBuilder<String>(
      valueListenable: ApawSkin.current,
      builder: (_, cur, __) => apawCard(
        onTap: () => showApawSkinPicker(context),
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
        child: Row(children: [
          apawIconChip('common-settings', size: 40),
          const SizedBox(width: 14),
          Expanded(child: Text('Look & feel', style: apawText(size: 16, color: ApawColors.forest, weight: FontWeight.w700))),
          Text(ApawSkin.label(cur), style: apawText(size: 14, color: ApawColors.muted)),
          const SizedBox(width: 6),
          Transform.flip(flipX: true, child: apawIcon('common-back', color: ApawColors.muted, size: 18)),
        ]),
      ),
    );

/// The top of every main screen: app logo, a title, and actions on the right.
Widget apawHeader(String app, String title,
        {List<Widget> actions = const [], String? subtitle, EdgeInsets padding = const EdgeInsets.fromLTRB(20, 12, 12, 8)}) =>
    Padding(
      padding: padding,
      child: Row(children: [
        apawLogo(app, size: 38),
        const SizedBox(width: 12),
        Expanded(
          child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [
            Text(title, maxLines: 1, overflow: TextOverflow.ellipsis, style: apawDisplay(size: 25)),
            if (subtitle != null)
              Text(subtitle, maxLines: 1, overflow: TextOverflow.ellipsis, style: apawText(size: 13.5, color: ApawColors.muted)),
          ]),
        ),
        ...actions,
      ]),
    );

/// A round header button with a pack icon (account, settings, filter ...).
Widget apawHeaderButton(String icon, String tooltip, VoidCallback onTap) => Padding(
      padding: const EdgeInsets.only(left: 6),
      child: Material(
        color: Colors.white,
        shape: const CircleBorder(side: BorderSide(color: ApawColors.sand)),
        child: InkWell(
          customBorder: const CircleBorder(),
          onTap: onTap,
          child: Tooltip(
            message: tooltip,
            child: SizedBox(width: 42, height: 42, child: Center(child: apawIcon(icon, color: ApawColors.forest, size: 22))),
          ),
        ),
      ),
    );

/// An icon on a soft rounded square.
Widget apawIconChip(String icon, {double size = 44, Color bg = ApawColors.peach, Color color = ApawColors.orange}) {
  Widget plain() => Container(
        width: size,
        height: size,
        decoration: BoxDecoration(color: bg, borderRadius: BorderRadius.circular(size * .3)),
        alignment: Alignment.center,
        child: apawIcon(icon, color: color, size: size * .52),
      );
  // Only the default tile becomes a regional badge; coloured ones (lost,
  // found, warnings) keep their meaning. Badges want 48px or more.
  if (bg != ApawColors.peach || color != ApawColors.orange || size < 36) return plain();
  return ValueListenableBuilder<String>(
    valueListenable: ApawSkin.current,
    builder: (_, skin, __) {
      if (skin == 'standard') return plain();
      final big = size < 48 ? 48.0 : size;
      return SizedBox(
        width: big,
        height: big,
        child: SvgPicture.network(ApawSkin.art(skin, 'badges', icon),
            width: big, height: big, excludeFromSemantics: true, placeholderBuilder: (_) => Center(child: plain())),
      );
    },
  );
}

/// The main call to action: orange, forest bold text.
Widget apawPrimary(String label, VoidCallback? onTap, {bool busy = false, String? icon}) => SizedBox(
      height: 54,
      width: double.infinity,
      child: FilledButton(
        onPressed: busy ? null : onTap,
        child: busy
            ? const SizedBox(width: 22, height: 22, child: CircularProgressIndicator(strokeWidth: 2.4, color: ApawColors.forest))
            : Row(mainAxisAlignment: MainAxisAlignment.center, children: [
                if (icon != null) ...[apawIcon(icon, color: ApawColors.forest, size: 22), const SizedBox(width: 8)],
                Flexible(child: Text(label, overflow: TextOverflow.ellipsis, style: GoogleFonts.figtree(fontSize: 17, fontWeight: FontWeight.w800))),
              ]),
      ),
    );

/// The second choice: white, forest text, sand border.
Widget apawSecondary(String label, VoidCallback? onTap, {String? icon}) => SizedBox(
      height: 50,
      width: double.infinity,
      child: OutlinedButton(
        onPressed: onTap,
        child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [
          if (icon != null) ...[apawIcon(icon, color: ApawColors.forest, size: 20), const SizedBox(width: 8)],
          Flexible(child: Text(label, overflow: TextOverflow.ellipsis)),
        ]),
      ),
    );

/// A card: cream, sand border, rounded.
Widget apawCard({required Widget child, EdgeInsets padding = const EdgeInsets.all(16), VoidCallback? onTap, Color color = ApawColors.cream}) =>
    ValueListenableBuilder<String>(
      valueListenable: ApawSkin.current,
      builder: (_, skin, __) {
        final paper = ApawSkin.paper[skin];
        final c = (color == ApawColors.cream && paper != null) ? Color.lerp(paper, Colors.white, .55)! : color;
        return Material(
          color: c,
          shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(18),
              side: BorderSide(color: paper == null ? ApawColors.sand : Color.lerp(paper, ApawColors.forest, .18)!)),
          clipBehavior: Clip.antiAlias,
          child: InkWell(onTap: onTap, child: Padding(padding: padding, child: child)),
        );
      },
    );

/// A feature line: orange icon, bold title, one line of detail.
Widget apawFeature(String icon, String title, String body) => Padding(
      padding: const EdgeInsets.symmetric(vertical: 7),
      child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
        apawIconChip(icon, size: 42),
        const SizedBox(width: 12),
        Expanded(
          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text(title, style: apawText(size: 16, color: ApawColors.forest, weight: FontWeight.w800)),
            const SizedBox(height: 2),
            Text(body, style: apawText(size: 13.5, color: ApawColors.muted, height: 1.35)),
          ]),
        ),
      ]),
    );

/// The One Tail One Meal line.
Widget apawMeals(String text) => Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(color: ApawColors.peach, borderRadius: BorderRadius.circular(16)),
      child: Row(children: [
        apawIcon('common-meals-funded', color: ApawColors.orange, size: 26),
        const SizedBox(width: 12),
        Expanded(child: Text(text, style: apawText(size: 14, height: 1.4))),
      ]),
    );

/// A section title inside a screen.
Widget apawSection(String title, {String? icon}) => Padding(
      padding: const EdgeInsets.fromLTRB(2, 18, 2, 10),
      child: Row(children: [
        if (icon != null) ...[apawIcon(icon, color: ApawColors.orange, size: 20), const SizedBox(width: 8)],
        Text(title, style: apawDisplay(size: 19)),
      ]),
    );

/// An empty screen: picture, title, one line, optional action.
Widget apawEmptyState(String art, String title, String body, {String? action, VoidCallback? onAction}) => Padding(
      padding: const EdgeInsets.fromLTRB(28, 28, 28, 28),
      child: Column(mainAxisSize: MainAxisSize.min, children: [
        apawEmpty(art, width: 220),
        const SizedBox(height: 14),
        Text(title, textAlign: TextAlign.center, style: apawDisplay(size: 22)),
        const SizedBox(height: 6),
        Text(body, textAlign: TextAlign.center, style: apawText(color: ApawColors.muted)),
        if (action != null && onAction != null) ...[const SizedBox(height: 18), apawPrimary(action, onAction)],
      ]),
    );

/// The bottom nav: pack icons (outline, filled when selected), same in every app.
Widget apawNavBar({required int index, required ValueChanged<int> onTap, required List<(String, String)> items}) =>
    NavigationBar(
      selectedIndex: index,
      onDestinationSelected: onTap,
      destinations: [
        for (final (icon, label) in items)
          NavigationDestination(
            icon: apawIcon(icon, color: ApawColors.muted, size: 24),
            selectedIcon: apawIcon('$icon-filled', color: ApawColors.forest, size: 24),
            label: label,
          ),
      ],
    );

/// A paid plan to choose (Yearly / Monthly ...).
Widget apawPlan(String title, String price, String note, bool selected, VoidCallback onTap, {String? badge}) =>
    GestureDetector(
      onTap: onTap,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 150),
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: selected ? Colors.white : ApawColors.cream,
          borderRadius: BorderRadius.circular(18),
          border: Border.all(color: selected ? ApawColors.orange : ApawColors.sand, width: selected ? 2.5 : 1),
        ),
        child: Row(children: [
          Container(
            width: 22,
            height: 22,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: selected ? ApawColors.orange : Colors.white,
              border: Border.all(color: selected ? ApawColors.orange : ApawColors.muted, width: 2),
            ),
            child: selected ? const Icon(Icons.check_rounded, size: 14, color: ApawColors.forest) : null,
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              Text(title, style: apawText(size: 17, color: ApawColors.forest, weight: FontWeight.w800)),
              const SizedBox(height: 2),
              Text('$price  ·  $note', style: apawText(size: 13.5, color: ApawColors.muted)),
            ]),
          ),
          if (badge != null)
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 9, vertical: 5),
              decoration: BoxDecoration(color: ApawColors.orange, borderRadius: BorderRadius.circular(999)),
              child: Text(badge, style: apawText(size: 12, color: ApawColors.forest, weight: FontWeight.w800)),
            ),
        ]),
      ),
    );

/// The top of a paid-plan page: logo, plan name, a promise.
Widget apawPlanHero(String app, String plan, String promise) => Column(children: [
      const SizedBox(height: 4),
      apawLogo(app, size: 76),
      const SizedBox(height: 12),
      Container(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 5),
        decoration: BoxDecoration(color: ApawColors.peach, borderRadius: BorderRadius.circular(999)),
        child: Row(mainAxisSize: MainAxisSize.min, children: [
          apawIcon('common-premium', color: ApawColors.orange, size: 16),
          const SizedBox(width: 6),
          Text(plan, style: apawText(size: 13, color: ApawColors.forest, weight: FontWeight.w800)),
        ]),
      ),
      const SizedBox(height: 10),
      Text(promise, textAlign: TextAlign.center, style: apawDisplay(size: 28)),
      const SizedBox(height: 16),
    ]);

// -------------------------------------------------------------- front door

/// One line of the welcome list: pack icon, title, detail.
class ApawFeature {
  const ApawFeature(this.icon, this.title, this.body);
  final String icon;
  final String title;
  final String body;
}

enum _ApawDoor { welcome, signIn, create, forgot }

const _apawConfirmedUrl = 'https://spotapaw.github.io/care-a-paw-site/confirmed/';

/// Every a-Paw app's front door, laid out like Spot a Paw's: the app's logo,
/// its promise, what it does (icons), the meals line, then create / sign in.
/// Sign in, create account, forgot password and "Check your email" talk to
/// Supabase directly; FlutterFlow's auth state follows the session.
class ApawFrontDoor extends StatefulWidget {
  const ApawFrontDoor({
    super.key,
    required this.app,
    required this.name,
    required this.promise,
    required this.blurb,
    required this.features,
    required this.meals,
    required this.homeRoute,
    this.guestLabel,
    this.guestRoute,
    this.width,
    this.height,
  });

  final String app;
  final String name;
  final String promise;
  final String blurb;
  final List<ApawFeature> features;
  final String meals;
  final String homeRoute;

  /// Optional "look around first" link for apps that are open to everyone
  /// (Feed-a-Paw): the label and the route it goes to without an account.
  final String? guestLabel;
  final String? guestRoute;
  final double? width;
  final double? height;

  @override
  State<ApawFrontDoor> createState() => _ApawFrontDoorState();
}

class _ApawFrontDoorState extends State<ApawFrontDoor> {
  _ApawDoor _mode = _ApawDoor.welcome;
  final _email = TextEditingController();
  final _password = TextEditingController();
  bool _busy = false;
  bool _hide = true;
  String _error = '';

  @override
  void dispose() {
    _email.dispose();
    _password.dispose();
    super.dispose();
  }

  void _go(_ApawDoor m) => setState(() {
        _mode = m;
        _error = '';
      });

  Future<void> _home() async {
    if (!mounted) return;
    GoRouter.of(context).prepareAuthEvent();
    context.goNamedAuth(widget.homeRoute, context.mounted);
  }

  bool _valid() {
    final e = _email.text.trim();
    if (!e.contains('@') || e.length < 5) {
      setState(() => _error = 'Enter your email address.');
      return false;
    }
    if (_mode != _ApawDoor.forgot && _password.text.length < 8) {
      setState(() => _error = 'Passwords are at least 8 characters.');
      return false;
    }
    return true;
  }

  Future<void> _signIn() async {
    if (!_valid()) return;
    setState(() {
      _busy = true;
      _error = '';
    });
    try {
      final res = await SupaFlow.client.auth.signInWithPassword(email: _email.text.trim(), password: _password.text);
      if (res.session != null) {
        await _home();
        return;
      }
    } on AuthException catch (e) {
      final m = '${e.code ?? ''} ${e.message}'.toLowerCase();
      if (m.contains('not confirmed') || m.contains('not_confirmed')) {
        setState(() => _busy = false);
        if (await _checkEmail()) await _home();
        return;
      }
      setState(() => _error = m.contains('invalid') ? 'That email and password don’t match.' : e.message);
    } catch (_) {
      setState(() => _error = 'Could not sign in. Check your signal and try again.');
    }
    if (mounted) setState(() => _busy = false);
  }

  Future<void> _create() async {
    if (!_valid()) return;
    setState(() {
      _busy = true;
      _error = '';
    });
    try {
      final res = await SupaFlow.client.auth
          .signUp(email: _email.text.trim(), password: _password.text, emailRedirectTo: _apawConfirmedUrl);
      if (res.session != null) {
        await _home();
        return;
      }
      setState(() => _busy = false);
      if (await _checkEmail()) await _home();
      return;
    } on AuthException catch (e) {
      final m = e.message.toLowerCase();
      setState(() => _error = m.contains('already') ? 'That email already has an account. Sign in instead.' : e.message);
    } catch (_) {
      setState(() => _error = 'Could not create your account. Please try again.');
    }
    if (mounted) setState(() => _busy = false);
  }

  Future<void> _forgot() async {
    if (!_valid()) return;
    setState(() {
      _busy = true;
      _error = '';
    });
    try {
      await SupaFlow.client.auth.resetPasswordForEmail(_email.text.trim());
    } catch (_) {}
    if (!mounted) return;
    setState(() => _busy = false);
    ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
        content: Text('If that email has an account, a reset link is on its way.'), duration: Duration(seconds: 5)));
    _go(_ApawDoor.signIn);
  }

  Future<bool> _checkEmail() async {
    final address = _email.text.trim();
    final secret = _password.text;
    var note = '';
    var busy = false;
    StreamSubscription<AuthState>? watch;
    final ok = await showModalBottomSheet<bool>(
      context: context,
      isScrollControlled: true,
      isDismissible: false,
      enableDrag: false,
      builder: (sheet) {
        watch ??= SupaFlow.client.auth.onAuthStateChange.listen((s) {
          if (s.session != null && Navigator.of(sheet).canPop()) Navigator.of(sheet).pop(true);
        });
        return apawThemed(StatefulBuilder(
          builder: (sheet, redraw) => SafeArea(
            top: false,
            child: Padding(
              padding: const EdgeInsets.fromLTRB(22, 4, 22, 16),
              child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [
                Center(child: apawIconChip('common-send', size: 64)),
                const SizedBox(height: 14),
                Text('Check your email', textAlign: TextAlign.center, style: apawDisplay(size: 26)),
                const SizedBox(height: 6),
                Text('We sent a link to $address. Tap it to confirm your account, then come back here.',
                    textAlign: TextAlign.center, style: apawText(color: ApawColors.muted)),
                const SizedBox(height: 4),
                Text('Not there? Look in Junk or Spam.',
                    textAlign: TextAlign.center, style: apawText(size: 13, color: ApawColors.muted)),
                if (note.isNotEmpty) ...[
                  const SizedBox(height: 12),
                  Text(note, textAlign: TextAlign.center, style: apawText(color: ApawColors.forest, weight: FontWeight.w700)),
                ],
                const SizedBox(height: 18),
                apawPrimary('I’ve confirmed it', () async {
                  redraw(() => busy = true);
                  try {
                    final r = await SupaFlow.client.auth.signInWithPassword(email: address, password: secret);
                    if (r.session != null && Navigator.of(sheet).canPop()) {
                      Navigator.of(sheet).pop(true);
                      return;
                    }
                  } on AuthException catch (e) {
                    final m = '${e.code ?? ''} ${e.message}'.toLowerCase();
                    redraw(() => note = m.contains('not confirmed') || m.contains('not_confirmed')
                        ? 'Not confirmed yet. Tap the link in the email first.'
                        : e.message);
                  } catch (_) {
                    redraw(() => note = 'Could not check. Try again.');
                  }
                  redraw(() => busy = false);
                }, busy: busy),
                const SizedBox(height: 10),
                apawSecondary('Send it again', busy
                    ? null
                    : () async {
                        redraw(() => busy = true);
                        try {
                          await SupaFlow.client.auth.resend(type: OtpType.signup, email: address, emailRedirectTo: _apawConfirmedUrl);
                          redraw(() => note = 'Sent again. It can take a minute.');
                        } catch (_) {
                          redraw(() => note = 'Just sent one. Wait a minute and try again.');
                        }
                        redraw(() => busy = false);
                      }),
                TextButton(onPressed: () => Navigator.of(sheet).pop(false), child: const Text('Use a different email')),
              ]),
            ),
          ),
        ));
      },
    );
    await watch?.cancel();
    return ok == true || SupaFlow.client.auth.currentSession != null;
  }

  Widget _link(String label, VoidCallback onTap) =>
      TextButton(onPressed: _busy ? null : onTap, child: Text(label));

  Widget _welcome() => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
        const SizedBox(height: 8),
        Center(
          child: Container(
            decoration: BoxDecoration(borderRadius: BorderRadius.circular(34), boxShadow: const [
              BoxShadow(color: Color(0x331F5148), blurRadius: 24, offset: Offset(0, 10)),
            ]),
            child: apawLogo(widget.app, size: 116),
          ),
        ),
        const SizedBox(height: 18),
        Text(widget.name, textAlign: TextAlign.center, style: apawDisplay(size: 34)),
        const SizedBox(height: 8),
        Text(widget.promise,
            textAlign: TextAlign.center, style: apawText(size: 18, color: ApawColors.ink, weight: FontWeight.w700, height: 1.3)),
        const SizedBox(height: 6),
        Text(widget.blurb, textAlign: TextAlign.center, style: apawText(size: 15, color: ApawColors.muted)),
        const SizedBox(height: 20),
        apawCard(
          color: const Color(0xEEFFFCF7),
          padding: const EdgeInsets.fromLTRB(16, 10, 16, 10),
          child: Column(children: [for (final f in widget.features) apawFeature(f.icon, f.title, f.body)]),
        ),
        const SizedBox(height: 12),
        apawMeals(widget.meals),
        const SizedBox(height: 22),
        apawPrimary('Create an account', () => _go(_ApawDoor.create)),
        const SizedBox(height: 6),
        _link('I already have an account', () => _go(_ApawDoor.signIn)),
        if (widget.guestLabel != null && widget.guestRoute != null)
          _link(widget.guestLabel!, () => context.goNamed(widget.guestRoute!)),
        const SizedBox(height: 2),
        Text('One a-Paw account works in all our apps.',
            textAlign: TextAlign.center, style: apawText(size: 12.5, color: ApawColors.muted)),
      ]);

  Widget _form() {
    final title = switch (_mode) {
      _ApawDoor.signIn => 'Welcome back',
      _ApawDoor.create => 'Create your account',
      _ApawDoor.forgot => 'Reset your password',
      _ApawDoor.welcome => '',
    };
    final line = switch (_mode) {
      _ApawDoor.signIn => 'Sign in with your a-Paw account.',
      _ApawDoor.create => 'One account for every a-Paw app.',
      _ApawDoor.forgot => 'We’ll email you a link to set a new one.',
      _ApawDoor.welcome => '',
    };
    return Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
      Align(
        alignment: Alignment.centerLeft,
        child: IconButton(
          tooltip: 'Back',
          onPressed: () => _go(_ApawDoor.welcome),
          icon: const Icon(Icons.arrow_back_rounded, color: ApawColors.forest),
        ),
      ),
      Center(child: apawLogo(widget.app, size: 76)),
      const SizedBox(height: 16),
      Text(title, textAlign: TextAlign.center, style: apawDisplay(size: 30)),
      const SizedBox(height: 4),
      Text(line, textAlign: TextAlign.center, style: apawText(color: ApawColors.muted)),
      const SizedBox(height: 24),
      TextField(
        controller: _email,
        keyboardType: TextInputType.emailAddress,
        autofillHints: const [AutofillHints.email],
        style: apawText(size: 16),
        decoration: const InputDecoration(labelText: 'Email'),
      ),
      if (_mode != _ApawDoor.forgot) ...[
        const SizedBox(height: 12),
        TextField(
          controller: _password,
          obscureText: _hide,
          autofillHints: [_mode == _ApawDoor.create ? AutofillHints.newPassword : AutofillHints.password],
          style: apawText(size: 16),
          decoration: InputDecoration(
            labelText: _mode == _ApawDoor.create ? 'Password (at least 8 characters)' : 'Password',
            suffixIcon: IconButton(
              tooltip: _hide ? 'Show password' : 'Hide password',
              icon: Icon(_hide ? Icons.visibility_outlined : Icons.visibility_off_outlined, color: ApawColors.muted),
              onPressed: () => setState(() => _hide = !_hide),
            ),
          ),
        ),
      ],
      if (_error.isNotEmpty) ...[
        const SizedBox(height: 12),
        Row(children: [
          apawIcon('common-warning', color: ApawColors.lost, size: 18),
          const SizedBox(width: 8),
          Expanded(child: Text(_error, style: apawText(size: 14, color: ApawColors.lost, weight: FontWeight.w600))),
        ]),
      ],
      const SizedBox(height: 20),
      if (_mode == _ApawDoor.signIn) apawPrimary('Sign in', _signIn, busy: _busy),
      if (_mode == _ApawDoor.create) apawPrimary('Create account', _create, busy: _busy),
      if (_mode == _ApawDoor.forgot) apawPrimary('Send reset link', _forgot, busy: _busy),
      const SizedBox(height: 8),
      if (_mode == _ApawDoor.signIn) _link('Forgot your password?', () => _go(_ApawDoor.forgot)),
      if (_mode == _ApawDoor.signIn) _link('New here? Create an account', () => _go(_ApawDoor.create)),
      if (_mode == _ApawDoor.create) _link('I already have an account', () => _go(_ApawDoor.signIn)),
      if (_mode == _ApawDoor.forgot) _link('Back to sign in', () => _go(_ApawDoor.signIn)),
    ]);
  }

  @override
  Widget build(BuildContext context) => apawThemed(Material(
        color: ApawColors.ivory,
        child: SizedBox(
          width: widget.width ?? double.infinity,
          height: widget.height ?? double.infinity,
          child: apawBackground(
            scene: 'onboarding',
            child: SafeArea(
              child: Center(
                child: ConstrainedBox(
                  constraints: const BoxConstraints(maxWidth: 520),
                  child: SingleChildScrollView(
                    padding: const EdgeInsets.fromLTRB(22, 18, 22, 24),
                    child: _mode == _ApawDoor.welcome ? _welcome() : _form(),
                  ),
                ),
              ),
            ),
          ),
        ),
      ));
}

const _apawLogos = <String, String>{
  'care': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><rect width="1024" height="1024" fill="#1F5148"/><g transform="translate(240 180) scale(22.916666666666668)" fill="#FF7900"><path d="M7.3 13.7C8.5 10.4 10 10 12 10s3.5.4 4.7 3.7c.8 1.2 2.1 2.1 2.1 3.9 0 2-1.6 3.1-3.4 2.5L12 19l-3.4 1.1c-1.8.6-3.4-.5-3.4-2.5 0-1.8 1.3-2.7 2.1-3.9Z"/><ellipse cx="5" cy="9" rx="1.7" ry="2.2"/><ellipse cx="9.4" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="14.6" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="19" cy="9" rx="1.7" ry="2.2"/></g><g fill="#1F5148"><g transform="translate(421 455) scale(7.5)"><path d="M12 20S3 14.4 3 8.6C3 3.6 9 2 12 6c3-4 9-2.4 9 2.6C21 14.4 12 20 12 20Z"/></g></g></svg>''',
  'track': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><rect width="1024" height="1024" fill="#1F5148"/><path d="M512 802S288 574 288 426a224 224 0 0 1 448 0c0 148-224 376-224 376Z" fill="#FF7900"/><g transform="translate(367 290) scale(12.083333333333334)" fill="#1F5148"><path d="M7.3 13.7C8.5 10.4 10 10 12 10s3.5.4 4.7 3.7c.8 1.2 2.1 2.1 2.1 3.9 0 2-1.6 3.1-3.4 2.5L12 19l-3.4 1.1c-1.8.6-3.4-.5-3.4-2.5 0-1.8 1.3-2.7 2.1-3.9Z"/><ellipse cx="5" cy="9" rx="1.7" ry="2.2"/><ellipse cx="9.4" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="14.6" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="19" cy="9" rx="1.7" ry="2.2"/></g></svg>''',
  'snap': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><rect width="1024" height="1024" fill="#1F5148"/><g fill="none" stroke="#F6F1E7" stroke-width="27" stroke-linecap="round" stroke-linejoin="round"><rect x="244" y="246" width="536" height="536" rx="56"/></g><g transform="translate(337 320) scale(14.583333333333334)" fill="#FF7900"><path d="M7.3 13.7C8.5 10.4 10 10 12 10s3.5.4 4.7 3.7c.8 1.2 2.1 2.1 2.1 3.9 0 2-1.6 3.1-3.4 2.5L12 19l-3.4 1.1c-1.8.6-3.4-.5-3.4-2.5 0-1.8 1.3-2.7 2.1-3.9Z"/><ellipse cx="5" cy="9" rx="1.7" ry="2.2"/><ellipse cx="9.4" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="14.6" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="19" cy="9" rx="1.7" ry="2.2"/></g><g fill="none" stroke="#F6F1E7" stroke-width="27" stroke-linecap="round" stroke-linejoin="round"><path d="m660 669 103-130M651 678q-18 54-64 53 13-24 22-42 16-29 42-11Z"/></g></svg>''',
  'feed': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><rect width="1024" height="1024" fill="#1F5148"/><path d="M224 544h576l-44 181a78 78 0 0 1-76 60H344a78 78 0 0 1-76-60Z" fill="#FF7900"/><g transform="translate(389 255) scale(10.25)" fill="#FF7900"><path d="M7.3 13.7C8.5 10.4 10 10 12 10s3.5.4 4.7 3.7c.8 1.2 2.1 2.1 2.1 3.9 0 2-1.6 3.1-3.4 2.5L12 19l-3.4 1.1c-1.8.6-3.4-.5-3.4-2.5 0-1.8 1.3-2.7 2.1-3.9Z"/><ellipse cx="5" cy="9" rx="1.7" ry="2.2"/><ellipse cx="9.4" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="14.6" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="19" cy="9" rx="1.7" ry="2.2"/></g></svg>''',
  'adopt': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><rect width="1024" height="1024" fill="#1F5148"/><g fill="none" stroke="#F6F1E7" stroke-width="27" stroke-linecap="round" stroke-linejoin="round"><path d="m226 453 286-243 286 243M278 415v376h468V415"/></g><g transform="translate(344 405) scale(14.0)" fill="#FF7900"><path d="M7.3 13.7C8.5 10.4 10 10 12 10s3.5.4 4.7 3.7c.8 1.2 2.1 2.1 2.1 3.9 0 2-1.6 3.1-3.4 2.5L12 19l-3.4 1.1c-1.8.6-3.4-.5-3.4-2.5 0-1.8 1.3-2.7 2.1-3.9Z"/><ellipse cx="5" cy="9" rx="1.7" ry="2.2"/><ellipse cx="9.4" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="14.6" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="19" cy="9" rx="1.7" ry="2.2"/></g></svg>''',
  'mind': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><rect width="1024" height="1024" fill="#1F5148"/><g transform="translate(224 190) scale(18.333333333333332)" fill="#FF7900"><path d="M7.3 13.7C8.5 10.4 10 10 12 10s3.5.4 4.7 3.7c.8 1.2 2.1 2.1 2.1 3.9 0 2-1.6 3.1-3.4 2.5L12 19l-3.4 1.1c-1.8.6-3.4-.5-3.4-2.5 0-1.8 1.3-2.7 2.1-3.9Z"/><ellipse cx="5" cy="9" rx="1.7" ry="2.2"/><ellipse cx="9.4" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="14.6" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="19" cy="9" rx="1.7" ry="2.2"/></g><g fill="none" stroke="#F6F1E7" stroke-width="27" stroke-linecap="round" stroke-linejoin="round"><circle cx="651" cy="608" r="66"/><path d="m605 655-133 133m40-40 34 34m-1-67 34 34"/></g></svg>''',
};

const _apawUi = <String, String>{
  'feed-about-cooking-drum-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="4" width="14" height="16" rx="4"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="M5 8h14M5 16h14M9 11v2m6-2v2"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M8 2h8M8 20v2m8-2v2"/></g></g></svg>''',
  'feed-about-cooking-drum': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="4" width="14" height="16" rx="4"/><path d="M5 8h14M5 16h14M9 11v2m6-2v2"/><path d="M8 2h8M8 20v2m8-2v2"/></g></g></svg>''',
  'feed-about-edible-plate-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="14" rx="10" ry="6"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="14" rx="6" ry="3"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M12 10c-5-1-5-7-5-7s7 0 5 7Zm0 0c0-5 5-7 5-7s3 6-5 7Z"/></g></g></svg>''',
  'feed-about-edible-plate': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="14" rx="10" ry="6"/><ellipse cx="12" cy="14" rx="6" ry="3"/><path d="M12 10c-5-1-5-7-5-7s7 0 5 7Zm0 0c0-5 5-7 5-7s3 6-5 7Z"/></g></g></svg>''',
  'feed-about-honesty-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6Z"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="M12 16s-5-3-5-6c0-3 3.5-4 5-1 1.5-3 5-2 5 1 0 3-5 6-5 6Z"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"></g></g></svg>''',
  'feed-about-honesty': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6Z"/><path d="M12 16s-5-3-5-6c0-3 3.5-4 5-1 1.5-3 5-2 5 1 0 3-5 6-5 6Z"/></g></g></svg>''',
  'feed-map-area-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="3.181818" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="17" rx="9" ry="4"/><path d="M17 7c0 4-5 9-5 9S7 11 7 7a5 5 0 0 1 10 0Z"/></g></g></svg>''',
  'feed-map-area': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="17" rx="9" ry="4"/><path d="M17 7c0 4-5 9-5 9S7 11 7 7a5 5 0 0 1 10 0Z"/></g></g></svg>''',
  'feed-map-feeding-spot-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10h18l-1.5 6.5A4 4 0 0 1 15.6 20H8.4a4 4 0 0 1-3.9-3.5Z"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M8 6V4m4 2V3m4 3V4"/></g></g></svg>''',
  'feed-map-feeding-spot': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10h18l-1.5 6.5A4 4 0 0 1 15.6 20H8.4a4 4 0 0 1-3.9-3.5Z"/><path d="M8 6V4m4 2V3m4 3V4"/></g></g></svg>''',
  'feed-map-round-done-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(0 0) scale(.76)"><path d="M3 10h18l-1.5 6.5A4 4 0 0 1 15.6 20H8.4a4 4 0 0 1-3.9-3.5Z"/></g></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><g transform="scale(.76)"></g></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><g transform="scale(.76)"><path d="M8 6V4m4 2V3m4 3V4"/></g><g transform="translate(13 13) scale(.42)"><path d="m5 12 4.5 4.5L19 7"/></g></g></g></svg>''',
  'feed-map-round-done': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(0 0) scale(.76)"><path d="M3 10h18l-1.5 6.5A4 4 0 0 1 15.6 20H8.4a4 4 0 0 1-3.9-3.5Z"/></g><g transform="scale(.76)"></g><g transform="scale(.76)"><path d="M8 6V4m4 2V3m4 3V4"/></g><g transform="translate(13 13) scale(.42)"><path d="m5 12 4.5 4.5L19 7"/></g></g></g></svg>''',
  'feed-nav-about-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="M12 11v6M12 7h.01"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"></g></g></svg>''',
  'feed-nav-about': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></g></g></svg>''',
  'feed-nav-driver-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="2"/><path d="M3 11h7m4 0h7M12 14v7"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"></g></g></svg>''',
  'feed-nav-driver': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="2"/><path d="M3 11h7m4 0h7M12 14v7"/></g></g></svg>''',
  'feed-nav-map-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="m3 5 6-2 6 3 6-2v15l-6 2-6-3-6 2Z"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="M9 3v15m6-12v15"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"></g></g></svg>''',
  'feed-nav-map': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m3 5 6-2 6 3 6-2v15l-6 2-6-3-6 2Z"/><path d="M9 3v15m6-12v15"/></g></g></svg>''',
  'feed-nav-stories-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(0 0) scale(.76)"><rect x="3" y="3" width="18" height="18" rx="3"/></g></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><g transform="scale(.76)"><path d="m4 17 5-5 4 4 3-3 5 5"/><circle cx="16" cy="8" r="1.2"/></g></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><g transform="scale(.76)"></g><g transform="translate(13 13) scale(.42)"><rect x="3" y="3" width="18" height="18" rx="3"/><path d="m4 17 5-5 4 4 3-3 5 5"/><circle cx="16" cy="8" r="1.2"/></g></g></g></svg>''',
  'feed-nav-stories': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(0 0) scale(.76)"><rect x="3" y="3" width="18" height="18" rx="3"/></g><g transform="scale(.76)"><path d="m4 17 5-5 4 4 3-3 5 5"/><circle cx="16" cy="8" r="1.2"/></g><g transform="scale(.76)"></g><g transform="translate(13 13) scale(.42)"><rect x="3" y="3" width="18" height="18" rx="3"/><path d="m4 17 5-5 4 4 3-3 5 5"/><circle cx="16" cy="8" r="1.2"/></g></g></g></svg>''',
  'feed-nav-today-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10h18l-1.5 6.5A4 4 0 0 1 15.6 20H8.4a4 4 0 0 1-3.9-3.5Z"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M8 6V4m4 2V3m4 3V4"/></g></g></svg>''',
  'feed-nav-today': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10h18l-1.5 6.5A4 4 0 0 1 15.6 20H8.4a4 4 0 0 1-3.9-3.5Z"/><path d="M8 6V4m4 2V3m4 3V4"/></g></g></svg>''',
  'feed-pickup-kilos-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="m8 8-4 13h16L16 8Z"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="M9 17h6"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="5" r="3"/></g></g></svg>''',
  'feed-pickup-kilos': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m8 8-4 13h16L16 8Z"/><path d="M9 17h6"/><circle cx="12" cy="5" r="3"/></g></g></svg>''',
  'feed-pickup-parcel-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="m3 7 9-4 9 4v12l-9 3-9-3Z"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="m3 7 9 4 9-4M12 11v11m-5-17 9 4"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"></g></g></svg>''',
  'feed-pickup-parcel': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m3 7 9-4 9 4v12l-9 3-9-3Z"/><path d="m3 7 9 4 9-4M12 11v11m-5-17 9 4"/></g></g></svg>''',
  'feed-role-driver-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M2 6h12v12H2Zm12 4h5l3 4v4h-8Z"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="M17 10v4h5"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="19" r="2"/><circle cx="18" cy="19" r="2"/></g></g></svg>''',
  'feed-role-driver': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M2 6h12v12H2Zm12 4h5l3 4v4h-8Z"/><path d="M17 10v4h5"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="19" r="2"/></g></g></svg>''',
  'feed-role-feeder-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="3.181818" stroke-linecap="round" stroke-linejoin="round"><path d="M2 15h4l3-3h6a2 2 0 0 1 0 4h-4m-5-1 3 6h7l6-7a2 2 0 0 0-3-2l-3 3M2 14v8"/><g transform="translate(7 -1) scale(.55)"><path d="M12 20S3 14.4 3 8.6C3 3.6 9 2 12 6c3-4 9-2.4 9 2.6C21 14.4 12 20 12 20Z"/></g></g></g></svg>''',
  'feed-role-feeder': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M2 15h4l3-3h6a2 2 0 0 1 0 4h-4m-5-1 3 6h7l6-7a2 2 0 0 0-3-2l-3 3M2 14v8"/><g transform="translate(7 -1) scale(.55)"><path d="M12 20S3 14.4 3 8.6C3 3.6 9 2 12 6c3-4 9-2.4 9 2.6C21 14.4 12 20 12 20Z"/></g></g></g></svg>''',
  'feed-role-supplier-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="m3 7 9-4 9 4v12l-9 3-9-3Z"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="m3 7 9 4 9-4M12 11v11m-5-17 9 4"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"></g></g></svg>''',
  'feed-role-supplier': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m3 7 9-4 9 4v12l-9 3-9-3Z"/><path d="m3 7 9 4 9-4M12 11v11m-5-17 9 4"/></g></g></svg>''',
  'feed-stop-animals-seen-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(-1 -1) scale(.84)"><path d="M7.3 13.7C8.5 10.4 10 10 12 10s3.5.4 4.7 3.7c.8 1.2 2.1 2.1 2.1 3.9 0 2-1.6 3.1-3.4 2.5L12 19l-3.4 1.1c-1.8.6-3.4-.5-3.4-2.5 0-1.8 1.3-2.7 2.1-3.9Z"/><ellipse cx="5" cy="9" rx="1.7" ry="2.2"/><ellipse cx="9.4" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="14.6" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="19" cy="9" rx="1.7" ry="2.2"/></g></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M17 14v7m3-9v9"/></g></g></svg>''',
  'feed-stop-animals-seen': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(-1 -1) scale(.84)"><path d="M7.3 13.7C8.5 10.4 10 10 12 10s3.5.4 4.7 3.7c.8 1.2 2.1 2.1 2.1 3.9 0 2-1.6 3.1-3.4 2.5L12 19l-3.4 1.1c-1.8.6-3.4-.5-3.4-2.5 0-1.8 1.3-2.7 2.1-3.9Z"/><ellipse cx="5" cy="9" rx="1.7" ry="2.2"/><ellipse cx="9.4" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="14.6" cy="5.3" rx="1.7" ry="2.3"/><ellipse cx="19" cy="9" rx="1.7" ry="2.2"/></g><path d="M17 14v7m3-9v9"/></g></g></svg>''',
  'feed-stop-note-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="3" width="16" height="18" rx="2"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="M8 8h8M8 12h8m-8 4h5"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"></g></g></svg>''',
  'feed-stop-note': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 8h8M8 12h8m-8 4h5"/></g></g></svg>''',
  'feed-team-finish-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="5" width="14" height="14" rx="3"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"></g></g></svg>''',
  'feed-team-finish': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="5" width="14" height="14" rx="3"/></g></g></svg>''',
  'feed-team-sign-in-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><circle cx="8" cy="8" r="5"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m12 12 9 9m-4-4 3-3m-6 0 3-3"/></g></g></svg>''',
  'feed-team-sign-in': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><circle cx="8" cy="8" r="5"/><path d="m12 12 9 9m-4-4 3-3m-6 0 3-3"/></g></g></svg>''',
  'feed-team-start-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="m7 3 14 9-14 9Z"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"></g></g></svg>''',
  'feed-team-start': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m7 3 14 9-14 9Z"/></g></g></svg>''',
  'feed-team-tally-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="m6 8 1 1 2-3m-3 8 1 1 2-3m3-4h5m-5 6h5"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"></g></g></svg>''',
  'feed-team-tally': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="m6 8 1 1 2-3m-3 8 1 1 2-3m3-4h5m-5 6h5"/></g></g></svg>''',
  'feed-today-counter-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="6" width="18" height="14" rx="3"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="M10 6v14m-3-9v4m7-5h3v6h-3Z"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M8 3h8"/></g></g></svg>''',
  'feed-today-counter': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="6" width="18" height="14" rx="3"/><path d="M10 6v14m-3-9v4m7-5h3v6h-3Z"/><path d="M8 3h8"/></g></g></svg>''',
  'feed-today-support-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="3.181818" stroke-linecap="round" stroke-linejoin="round"><path d="M2 15h4l3-3h6a2 2 0 0 1 0 4h-4m-5-1 3 6h7l6-7a2 2 0 0 0-3-2l-3 3M2 14v8"/><g transform="translate(7 -1) scale(.55)"><path d="M12 20S3 14.4 3 8.6C3 3.6 9 2 12 6c3-4 9-2.4 9 2.6C21 14.4 12 20 12 20Z"/></g></g></g></svg>''',
  'feed-today-support': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M2 15h4l3-3h6a2 2 0 0 1 0 4h-4m-5-1 3 6h7l6-7a2 2 0 0 0-3-2l-3 3M2 14v8"/><g transform="translate(7 -1) scale(.55)"><path d="M12 20S3 14.4 3 8.6C3 3.6 9 2 12 6c3-4 9-2.4 9 2.6C21 14.4 12 20 12 20Z"/></g></g></g></svg>''',
  'feed-today-truck-fund-filled': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><defs><mask id="cut" maskUnits="userSpaceOnUse" x="-2" y="-2" width="28" height="28"><g fill="white" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M4 10h16v10H4Z"/></g><g fill="none" stroke="black" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="M8 13v4m4-4v4m4-4v4"/></g></mask></defs><rect width="24" height="24" fill="currentColor" mask="url(#cut)"/><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7h18"/><g transform="translate(8 0) scale(.33)"><path d="M12 20S3 14.4 3 8.6C3 3.6 9 2 12 6c3-4 9-2.4 9 2.6C21 14.4 12 20 12 20Z"/></g></g></g></svg>''',
  'feed-today-truck-fund': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M4 10h16v10H4Z"/><path d="M8 13v4m4-4v4m4-4v4"/><path d="M3 7h18"/><g transform="translate(8 0) scale(.33)"><path d="M12 20S3 14.4 3 8.6C3 3.6 9 2 12 6c3-4 9-2.4 9 2.6C21 14.4 12 20 12 20Z"/></g></g></g></svg>''',
  'common-account': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="7" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2Z"/></g></g></svg>''',
  'common-add': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></g></g></svg>''',
  'common-attach': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(1.2 1.2) scale(.9)"><path d="m9 12 6-6a3 3 0 0 1 4 4L9 20a5 5 0 0 1-7-7L13 2m-8 14a2 2 0 0 0 3 0l8-8"/></g></g></g></svg>''',
  'common-back': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m14 5-7 7 7 7M7 12h14"/></g></g></svg>''',
  'common-block': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></g></g></svg>''',
  'common-calendar': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M3 10h18M8 14h2m4 0h2m-8 3h2"/><path d="M7 3v4m10-4v4"/></g></g></svg>''',
  'common-camera': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7h4l2-3h6l2 3h4v13H3Z"/><circle cx="12" cy="13" r="4"/></g></g></svg>''',
  'common-clock': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></g></g></svg>''',
  'common-close': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m6 6 12 12M18 6 6 18"/></g></g></svg>''',
  'common-copy': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><rect x="8" y="8" width="13" height="13" rx="2"/><path d="M16 5V3H3v13h2"/></g></g></svg>''',
  'common-delete': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M5 7h14l-1 13H6Z"/><path d="M9 10v7m6-7v7"/><path d="M3 7h18M9 7V3h6v4"/></g></g></svg>''',
  'common-done': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 4.5 4.5L19 7"/></g></g></svg>''',
  'common-edit': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m4 15 11-11a2.8 2.8 0 0 1 4 4L8 19l-5 2Z"/><path d="m13 6 4 4"/><path d="M13 21h8"/></g></g></svg>''',
  'common-filter': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M3 4h18l-7 8v7l-4 2v-9Z"/></g></g></svg>''',
  'common-info': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></g></g></svg>''',
  'common-location': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M19 9c0 5-7 12-7 12S5 14 5 9a7 7 0 0 1 14 0Z"/><circle cx="12" cy="9" r="2.5"/></g></g></svg>''',
  'common-meals-funded': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10h18l-1.5 6.5A4 4 0 0 1 15.6 20H8.4a4 4 0 0 1-3.9-3.5Z"/><path d="M12 17s-3-1.7-3-3.3c0-1.8 2-2.3 3-.9 1-1.4 3-.9 3 .9 0 1.6-3 3.3-3 3.3Z"/><path d="M8 6V4m4 2V3m4 3V4"/></g></g></svg>''',
  'common-message': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M21 5v11a2 2 0 0 1-2 2H9l-6 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2Z"/><path d="M7 8h10M7 12h6"/></g></g></svg>''',
  'common-more': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><circle cx="5" cy="12" r="1.4"/><circle cx="12" cy="12" r="1.4"/><circle cx="19" cy="12" r="1.4"/></g></g></svg>''',
  'common-notifications': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M5 17h14l-2-3V9a5 5 0 0 0-10 0v5Z"/><path d="M10 21h4M12 2v2"/></g></g></svg>''',
  'common-open-website': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M11 4H4v16h16v-7"/><path d="M14 3h7v7M21 3 10 14"/></g></g></svg>''',
  'common-photo-gallery': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="3"/><path d="m4 17 5-5 4 4 3-3 5 5"/><circle cx="16" cy="8" r="1.2"/></g></g></svg>''',
  'common-premium': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/></g></g></svg>''',
  'common-privacy': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6Z"/><path d="m8 11 3 3 5-5"/></g></g></svg>''',
  'common-qr-code': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="6" height="6" rx="1"/><rect x="15" y="3" width="6" height="6" rx="1"/><rect x="3" y="15" width="6" height="6" rx="1"/><path d="M6 6h.01M18 6h.01M6 18h.01"/><path d="M15 15h3v3h3v3h-6M21 13v1M12 3v3M3 12h3m6 0v9"/></g></g></svg>''',
  'common-report': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M5 4c5-4 9 4 15 0v10c-6 4-10-4-15 0Z"/><path d="M5 3v19"/></g></g></svg>''',
  'common-restore-purchases': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M4 10a8 8 0 1 1 0 6M4 4v6h6M12 7v5l3 2"/></g></g></svg>''',
  'common-search': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></g></g></svg>''',
  'common-send': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m3 3 18 9-18 9 4-9Z"/><path d="M7 12h14"/></g></g></svg>''',
  'common-settings': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path transform="translate(2 0) scale(.83)" d="m9 3 6 0 .6 3 2 .9 2.7-1 3 5.2-2.2 2 .1 2.1 2.1 1.8-3 5.2-2.8-1-1.9 1-.6 2.8H9l-.6-2.8-1.9-1-2.8 1-3-5.2 2.1-1.8.1-2.1-2.2-2 3-5.2 2.7 1 2-.9Z"/><circle cx="12" cy="12" r="3"/></g></g></svg>''',
  'common-share': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="5" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8 10.5 7.4-4M8 13.5l7.4 4"/></g></g></svg>''',
  'common-sign-out': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="M11 3H4v18h7"/><path d="M10 12h11m-4-4 4 4-4 4"/></g></g></svg>''',
  'common-warning': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"><g transform="translate(1.44 1.44) scale(.88)"><g fill="none" stroke="currentColor" stroke-width="2.272727" stroke-linecap="round" stroke-linejoin="round"><path d="m10.3 4-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.7-3l-8-14a2 2 0 0 0-3.4 0Z"/><path d="M12 9v5m0 3h.01"/></g></g></svg>''',
};

const _apawEmpty = <String, String>{
  'feed-empty-no-rounds': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 160"><path d="M57 62c-8-36 27-48 58-42 33-11 77 4 75 41 22 28 3 69-32 71H82c-39-2-48-43-25-70Z" fill="#F6F1E7"/><g transform="translate(79 33) scale(3.4)" fill="none" stroke="#1F5148" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"><path d="M2 6h12v12H2Zm12 4h5l3 4v4h-8Z"/><path d="M17 10v4h5"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="19" r="2"/></g><g fill="none" stroke="#FF7900" stroke-width="3" stroke-linecap="round"><path d="M42 59v10m-5-5h10M191 97v8m-4-4h8"/><circle cx="181" cy="42" r="4"/></g><path d="M54 137h132" stroke="#1F5148" stroke-width="2" stroke-linecap="round"/></svg>''',
  'feed-empty-no-stories': r'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 160"><path d="M57 62c-8-36 27-48 58-42 33-11 77 4 75 41 22 28 3 69-32 71H82c-39-2-48-43-25-70Z" fill="#F6F1E7"/><g transform="translate(79 33) scale(3.4)" fill="none" stroke="#1F5148" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(0 0) scale(.76)"><rect x="3" y="3" width="18" height="18" rx="3"/></g><g transform="scale(.76)"><path d="m4 17 5-5 4 4 3-3 5 5"/><circle cx="16" cy="8" r="1.2"/></g><g transform="scale(.76)"></g><g transform="translate(13 13) scale(.42)"><rect x="3" y="3" width="18" height="18" rx="3"/><path d="m4 17 5-5 4 4 3-3 5 5"/><circle cx="16" cy="8" r="1.2"/></g></g><g fill="none" stroke="#FF7900" stroke-width="3" stroke-linecap="round"><path d="M42 59v10m-5-5h10M191 97v8m-4-4h8"/><circle cx="181" cy="42" r="4"/></g><path d="M54 137h132" stroke="#1F5148" stroke-width="2" stroke-linecap="round"/></svg>''',
};
