// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final aboutPageHandle = ffai.ProjectPageHandle<AboutPageParams, AboutPageState>(
  name: "AboutPage",
  key: "Scaffold_7o63x918",
  route: "about",
  params: const AboutPageParams(),
  state: const AboutPageState(),
  widgets: AboutPageWidgets.tree,
);

final class AboutPageParams {
  const AboutPageParams();
}

final class AboutPageState {
  const AboutPageState();
  ffai.ProjectStateFieldHandle get fund =>
      const ffai.ProjectStateFieldHandle(
        name: "fund",
        key: "b8b0eech",
        typeName: "List<PostgresRow>",
      );
}

abstract final class AboutPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_7o63x918",
      type: "Scaffold",
      path: "AboutPage",
      name: "AboutPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "about-skin",
            type: "Stack",
            path: "AboutPage.body[0]",
            name: "AboutSkin",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_f7lquo1c",
                type: "Container",
                path: "AboutPage.body[0].children[0]",
                name: "AboutBackdrop",
              ),
              ffai.ProjectWidgetHandle(
                key: "about-content",
                type: "Container",
                path: "AboutPage.body[0].children[1]",
                name: "AboutContent",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_a4mf6bd3",
                    type: "Container",
                    path: "AboutPage.body[0].children[1].children[0]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_grza0aw7",
                        type: "Column",
                        path: "AboutPage.body[0].children[1].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_zx3toi2f",
                            type: "Container",
                            path: "AboutPage.body[0].children[1].children[0].children[0].children[0]",
                            name: "AboutHeader",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_3ek3rcl2",
                            type: "Text",
                            path: "AboutPage.body[0].children[1].children[0].children[0].children[1]",
                            name: "AboutHeading",
                            text: "No stray should go hungry.",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_oha9emu2",
                            type: "Text",
                            path: "AboutPage.body[0].children[1].children[0].children[0].children[2]",
                            name: "AboutWords",
                            text: "A truck collects meat trimmings from partner butchers each morning, cooks them on board, and follows the same round through the streets where the colonies live. This app shows that work as it happens.",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_az8i2tm1",
                            type: "Text",
                            path: "AboutPage.body[0].children[1].children[0].children[0].children[3]",
                            name: "AboutMoney",
                            text: "Every meal in this app was cooked and handed out by the One Tail One Meal team. You can follow the round, read the stories and see the count rise. The wider story lives on onetailonemeal.com.",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_j0a5kwkc",
                            type: "Button",
                            path: "AboutPage.body[0].children[1].children[0].children[0].children[4]",
                            name: "GiveButton",
                            text: "Follow the truck on onetailonemeal.com",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_0jfnh1x5",
                type: "Container",
                path: "AboutPage.body[0].children[2]",
                name: "AboutBar",
              ),
            ],
          ),
        ],
      },
    ),
  );
}

