// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final accountPageHandle = ffai.ProjectPageHandle<AccountPageParams, AccountPageState>(
  name: "AccountPage",
  key: "Scaffold_k9nl9myo",
  route: "account",
  params: const AccountPageParams(),
  state: const AccountPageState(),
  widgets: AccountPageWidgets.tree,
);

final class AccountPageParams {
  const AccountPageParams();
}

final class AccountPageState {
  const AccountPageState();
}

abstract final class AccountPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_k9nl9myo",
      type: "Scaffold",
      path: "AccountPage",
      name: "AccountPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_2v75z61e",
            type: "Container",
            path: "AccountPage.body[0]",
            name: "AccountBody",
          ),
        ],
      },
    ),
  );
}

