// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final driverPageHandle = ffai.ProjectPageHandle<DriverPageParams, DriverPageState>(
  name: "DriverPage",
  key: "Scaffold_1o5d9e07",
  route: "driver",
  params: const DriverPageParams(),
  state: const DriverPageState(),
  widgets: DriverPageWidgets.tree,
);

final class DriverPageParams {
  const DriverPageParams();
}

final class DriverPageState {
  const DriverPageState();
  ffai.ProjectStateFieldHandle get onTheRoad =>
      const ffai.ProjectStateFieldHandle(
        name: "onTheRoad",
        key: "lpv6kte7",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get runId =>
      const ffai.ProjectStateFieldHandle(
        name: "runId",
        key: "yhvk75er",
        typeName: "String",
      );
}

abstract final class DriverPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_1o5d9e07",
      type: "Scaffold",
      path: "DriverPage",
      name: "DriverPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_pn6op4dl",
            type: "AppBar",
            path: "DriverPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_ybsncio4",
                  type: "Text",
                  path: "DriverPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Today",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_9fa9vthk",
            type: "Container",
            path: "DriverPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_qkoldesr",
                type: "Column",
                path: "DriverPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_qtv66hof",
                    type: "Text",
                    path: "DriverPage.body[0].children[0].children[0]",
                    name: "RoundHeading",
                    text: "The round",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_afarirt3",
                    type: "Text",
                    path: "DriverPage.body[0].children[0].children[1]",
                    name: "RoundWords",
                    text: "Start the day, then log each stop as you go.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_ox047bt4",
                    type: "Button",
                    path: "DriverPage.body[0].children[0].children[2]",
                    name: "StartRunButton",
                    text: "Start the round",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_2fog88v7",
                    type: "Button",
                    path: "DriverPage.body[0].children[0].children[3]",
                    name: "LogStopButton",
                    text: "Log a stop",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_zmdjnht0",
                    type: "Button",
                    path: "DriverPage.body[0].children[0].children[4]",
                    name: "LogPickupButton",
                    text: "Log a pickup",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_zfzjqb0v",
                    type: "Button",
                    path: "DriverPage.body[0].children[0].children[5]",
                    name: "FinishRunButton",
                    text: "Finish the round",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

