// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final pickupPageHandle = ffai.ProjectPageHandle<PickupPageParams, PickupPageState>(
  name: "PickupPage",
  key: "Scaffold_pg7c44kz",
  route: "pickup",
  params: const PickupPageParams(),
  state: const PickupPageState(),
  widgets: PickupPageWidgets.tree,
);

final class PickupPageParams {
  const PickupPageParams();
}

final class PickupPageState {
  const PickupPageState();
  ffai.ProjectStateFieldHandle get butcher =>
      const ffai.ProjectStateFieldHandle(
        name: "butcher",
        key: "1g9cdq1c",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get kilos =>
      const ffai.ProjectStateFieldHandle(
        name: "kilos",
        key: "h9sxio2i",
        typeName: "Double",
      );
  ffai.ProjectStateFieldHandle get note =>
      const ffai.ProjectStateFieldHandle(
        name: "note",
        key: "wieanu1s",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get runId =>
      const ffai.ProjectStateFieldHandle(
        name: "runId",
        key: "yzx2taz6",
        typeName: "String",
      );
}

abstract final class PickupPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_pg7c44kz",
      type: "Scaffold",
      path: "PickupPage",
      name: "PickupPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_twmu0ua7",
            type: "AppBar",
            path: "PickupPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_qhtasw1t",
                  type: "Text",
                  path: "PickupPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "A pickup",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_8betwhp6",
            type: "Container",
            path: "PickupPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_i93rfsuo",
                type: "Column",
                path: "PickupPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_55wecq7a",
                    type: "Text",
                    path: "PickupPage.body[0].children[0].children[0]",
                    name: "PickupWords",
                    text: "What the butcher put aside this morning.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_jailsc5x",
                    type: "TextField",
                    path: "PickupPage.body[0].children[0].children[1]",
                    name: "ButcherField",
                    text: "Which butcher",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_1r3kp90x",
                    type: "TextField",
                    path: "PickupPage.body[0].children[0].children[2]",
                    name: "KilosField",
                    text: "Kilos",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_75bgrwkw",
                    type: "TextField",
                    path: "PickupPage.body[0].children[0].children[3]",
                    name: "PickupNoteField",
                    text: "Note",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_h50rc8xs",
                    type: "Button",
                    path: "PickupPage.body[0].children[0].children[4]",
                    name: "SavePickupButton",
                    text: "Save the pickup",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

