// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final pickupPageHandle = ffai.ProjectPageHandle<PickupPageParams, PickupPageState>(
  name: "PickupPage",
  key: "Scaffold_pg7c44kz",
  route: "pickup",
  params: const PickupPageParams(),
  state: const PickupPageState(),
  widgets: PickupPageWidgets.tree,
);

final class PickupPageParams {
  const PickupPageParams();
}

final class PickupPageState {
  const PickupPageState();
  ffai.ProjectStateFieldHandle get butcher =>
      const ffai.ProjectStateFieldHandle(
        name: "butcher",
        key: "1g9cdq1c",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get kilos =>
      const ffai.ProjectStateFieldHandle(
        name: "kilos",
        key: "h9sxio2i",
        typeName: "Double",
      );
  ffai.ProjectStateFieldHandle get note =>
      const ffai.ProjectStateFieldHandle(
        name: "note",
        key: "wieanu1s",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get runId =>
      const ffai.ProjectStateFieldHandle(
        name: "runId",
        key: "yzx2taz6",
        typeName: "String",
      );
}

abstract final class PickupPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_pg7c44kz",
      type: "Scaffold",
      path: "PickupPage",
      name: "PickupPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "pickup-skin",
            type: "Stack",
            path: "PickupPage.body[0]",
            name: "PickupSkin",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_gmzuialv",
                type: "Container",
                path: "PickupPage.body[0].children[0]",
                name: "PickupBackdrop",
              ),
              ffai.ProjectWidgetHandle(
                key: "pickup-content",
                type: "Container",
                path: "PickupPage.body[0].children[1]",
                name: "PickupContent",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_8betwhp6",
                    type: "Container",
                    path: "PickupPage.body[0].children[1].children[0]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_i93rfsuo",
                        type: "Column",
                        path: "PickupPage.body[0].children[1].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_3ycw0gzp",
                            type: "Container",
                            path: "PickupPage.body[0].children[1].children[0].children[0].children[0]",
                            name: "TopBar",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_3b8twubh",
                            type: "Container",
                            path: "PickupPage.body[0].children[1].children[0].children[0].children[1]",
                            name: "PickupForm",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

