// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final signInPageHandle = ffai.ProjectPageHandle<SignInPageParams, SignInPageState>(
  name: "SignInPage",
  key: "Scaffold_9is36mmq",
  route: "sign-in",
  params: const SignInPageParams(),
  state: const SignInPageState(),
  widgets: SignInPageWidgets.tree,
);

final class SignInPageParams {
  const SignInPageParams();
}

final class SignInPageState {
  const SignInPageState();
  ffai.ProjectStateFieldHandle get email =>
      const ffai.ProjectStateFieldHandle(
        name: "email",
        key: "jxbbmo6p",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get password =>
      const ffai.ProjectStateFieldHandle(
        name: "password",
        key: "hn3acwyc",
        typeName: "String",
      );
}

abstract final class SignInPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_9is36mmq",
      type: "Scaffold",
      path: "SignInPage",
      name: "SignInPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_aon05h9g",
            type: "Container",
            path: "SignInPage.body[0]",
            name: "FrontDoor",
          ),
        ],
      },
    ),
  );
}

