// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final stopPageHandle = ffai.ProjectPageHandle<StopPageParams, StopPageState>(
  name: "StopPage",
  key: "Scaffold_lj0lvf5k",
  route: "stop",
  params: const StopPageParams(),
  state: const StopPageState(),
  widgets: StopPageWidgets.tree,
);

final class StopPageParams {
  const StopPageParams();
}

final class StopPageState {
  const StopPageState();
  ffai.ProjectStateFieldHandle get meals =>
      const ffai.ProjectStateFieldHandle(
        name: "meals",
        key: "sw0rmee0",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get note =>
      const ffai.ProjectStateFieldHandle(
        name: "note",
        key: "0rta1pgo",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get photoUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "photoUrl",
        key: "k82zigg2",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get runId =>
      const ffai.ProjectStateFieldHandle(
        name: "runId",
        key: "ly9lvf8b",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get seen =>
      const ffai.ProjectStateFieldHandle(
        name: "seen",
        key: "4vw7ybd5",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get spotId =>
      const ffai.ProjectStateFieldHandle(
        name: "spotId",
        key: "tijg8um3",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get spotName =>
      const ffai.ProjectStateFieldHandle(
        name: "spotName",
        key: "twycdn9g",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get spots =>
      const ffai.ProjectStateFieldHandle(
        name: "spots",
        key: "izx96nho",
        typeName: "List<PostgresRow>",
      );
}

abstract final class StopPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_lj0lvf5k",
      type: "Scaffold",
      path: "StopPage",
      name: "StopPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "stop-skin",
            type: "Stack",
            path: "StopPage.body[0]",
            name: "StopSkin",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_saho8tkd",
                type: "Container",
                path: "StopPage.body[0].children[0]",
                name: "StopBackdrop",
              ),
              ffai.ProjectWidgetHandle(
                key: "stop-content",
                type: "Container",
                path: "StopPage.body[0].children[1]",
                name: "StopContent",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_3y45sqpe",
                    type: "Container",
                    path: "StopPage.body[0].children[1].children[0]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_m8c03tk5",
                        type: "Column",
                        path: "StopPage.body[0].children[1].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_g0eu3b1o",
                            type: "Container",
                            path: "StopPage.body[0].children[1].children[0].children[0].children[0]",
                            name: "TopBar",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_f8keifl1",
                            type: "Container",
                            path: "StopPage.body[0].children[1].children[0].children[0].children[1]",
                            name: "StopForm",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

