// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final stopPageHandle = ffai.ProjectPageHandle<StopPageParams, StopPageState>(
  name: "StopPage",
  key: "Scaffold_lj0lvf5k",
  route: "stop",
  params: const StopPageParams(),
  state: const StopPageState(),
  widgets: StopPageWidgets.tree,
);

final class StopPageParams {
  const StopPageParams();
}

final class StopPageState {
  const StopPageState();
  ffai.ProjectStateFieldHandle get meals =>
      const ffai.ProjectStateFieldHandle(
        name: "meals",
        key: "sw0rmee0",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get note =>
      const ffai.ProjectStateFieldHandle(
        name: "note",
        key: "0rta1pgo",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get runId =>
      const ffai.ProjectStateFieldHandle(
        name: "runId",
        key: "ly9lvf8b",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get seen =>
      const ffai.ProjectStateFieldHandle(
        name: "seen",
        key: "4vw7ybd5",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get spotId =>
      const ffai.ProjectStateFieldHandle(
        name: "spotId",
        key: "tijg8um3",
        typeName: "String",
      );
}

abstract final class StopPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_lj0lvf5k",
      type: "Scaffold",
      path: "StopPage",
      name: "StopPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_8vpiurym",
            type: "AppBar",
            path: "StopPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_urzwxqvo",
                  type: "Text",
                  path: "StopPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "A stop",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_3y45sqpe",
            type: "Container",
            path: "StopPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_m8c03tk5",
                type: "Column",
                path: "StopPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_pf1m4q4h",
                    type: "Text",
                    path: "StopPage.body[0].children[0].children[0]",
                    name: "StopWords",
                    text: "Log it as you leave, while it is fresh.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_fnc1ngm5",
                    type: "TextField",
                    path: "StopPage.body[0].children[0].children[1]",
                    name: "SpotField",
                    text: "Which place",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_m5vakewf",
                    type: "TextField",
                    path: "StopPage.body[0].children[0].children[2]",
                    name: "MealsField",
                    text: "Meals served",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_52bnrxaw",
                    type: "TextField",
                    path: "StopPage.body[0].children[0].children[3]",
                    name: "SeenField",
                    text: "Animals seen",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_ssq6gd8i",
                    type: "TextField",
                    path: "StopPage.body[0].children[0].children[4]",
                    name: "StopNoteField",
                    text: "Anything worth saying",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_6xdknv8c",
                    type: "Button",
                    path: "StopPage.body[0].children[0].children[5]",
                    name: "SaveStopButton",
                    text: "Save this stop",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

