// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final storiesPageHandle = ffai.ProjectPageHandle<StoriesPageParams, StoriesPageState>(
  name: "StoriesPage",
  key: "Scaffold_sh31n4cg",
  route: "stories",
  params: const StoriesPageParams(),
  state: const StoriesPageState(),
  widgets: StoriesPageWidgets.tree,
);

final class StoriesPageParams {
  const StoriesPageParams();
}

final class StoriesPageState {
  const StoriesPageState();
  ffai.ProjectStateFieldHandle get stories =>
      const ffai.ProjectStateFieldHandle(
        name: "stories",
        key: "0okcngp7",
        typeName: "List<PostgresRow>",
      );
}

abstract final class StoriesPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_sh31n4cg",
      type: "Scaffold",
      path: "StoriesPage",
      name: "StoriesPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "stories-skin",
            type: "Stack",
            path: "StoriesPage.body[0]",
            name: "StoriesSkin",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_s6nmcqzg",
                type: "Container",
                path: "StoriesPage.body[0].children[0]",
                name: "StoriesBackdrop",
              ),
              ffai.ProjectWidgetHandle(
                key: "stories-content",
                type: "Container",
                path: "StoriesPage.body[0].children[1]",
                name: "StoriesContent",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_tapxo0rg",
                    type: "Column",
                    path: "StoriesPage.body[0].children[1].children[0]",
                    name: "StoriesBody",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_jvys2v09",
                        type: "Container",
                        path: "StoriesPage.body[0].children[1].children[0].children[0]",
                        name: "StoriesHeader",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_fggtrpzx",
                        type: "Container",
                        path: "StoriesPage.body[0].children[1].children[0].children[1]",
                        name: "StoriesEmpty",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "ListView_u7012p90",
                        type: "ListView",
                        path: "StoriesPage.body[0].children[1].children[0].children[2]",
                        name: "StoryList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Card_7ztxja1d",
                            type: "Card",
                            path: "StoriesPage.body[0].children[1].children[0].children[2].children[0]",
                            name: "Card",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_o809r5mb",
                                type: "Column",
                                path: "StoriesPage.body[0].children[1].children[0].children[2].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Image_zqb4reg1",
                                    type: "Image",
                                    path: "StoriesPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0]",
                                    name: "Image",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_4m5d2nds",
                                    type: "Text",
                                    path: "StoriesPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_uaghrxhj",
                                    type: "Text",
                                    path: "StoriesPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_rjb594rs",
                                    type: "Text",
                                    path: "StoriesPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

