// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final storiesPageHandle = ffai.ProjectPageHandle<StoriesPageParams, StoriesPageState>(
  name: "StoriesPage",
  key: "Scaffold_sh31n4cg",
  route: "stories",
  params: const StoriesPageParams(),
  state: const StoriesPageState(),
  widgets: StoriesPageWidgets.tree,
);

final class StoriesPageParams {
  const StoriesPageParams();
}

final class StoriesPageState {
  const StoriesPageState();
  ffai.ProjectStateFieldHandle get stories =>
      const ffai.ProjectStateFieldHandle(
        name: "stories",
        key: "0okcngp7",
        typeName: "List<PostgresRow>",
      );
}

abstract final class StoriesPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_sh31n4cg",
      type: "Scaffold",
      path: "StoriesPage",
      name: "StoriesPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_jvydxjxd",
            type: "AppBar",
            path: "StoriesPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_20dozi7g",
                  type: "Text",
                  path: "StoriesPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "From the street",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "ListView_8ryng321",
            type: "ListView",
            path: "StoriesPage.body[0]",
            name: "StoryList",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Card_1lixfdng",
                type: "Card",
                path: "StoriesPage.body[0].children[0]",
                name: "Card",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_2loi8se5",
                    type: "Column",
                    path: "StoriesPage.body[0].children[0].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Image_8pncx8ro",
                        type: "Image",
                        path: "StoriesPage.body[0].children[0].children[0].children[0]",
                        name: "StoryPhoto",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_1v5nnzdv",
                        type: "Text",
                        path: "StoriesPage.body[0].children[0].children[0].children[1]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_xbejjpq3",
                        type: "Text",
                        path: "StoriesPage.body[0].children[0].children[0].children[2]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_3favsbz4",
                        type: "Text",
                        path: "StoriesPage.body[0].children[0].children[0].children[3]",
                        name: "Text",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

