// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final todayPageHandle = ffai.ProjectPageHandle<TodayPageParams, TodayPageState>(
  name: "TodayPage",
  key: "Scaffold_go7ytkf6",
  route: "",
  params: const TodayPageParams(),
  state: const TodayPageState(),
  widgets: TodayPageWidgets.tree,
);

final class TodayPageParams {
  const TodayPageParams();
}

final class TodayPageState {
  const TodayPageState();
  ffai.ProjectStateFieldHandle get mealsAllTime =>
      const ffai.ProjectStateFieldHandle(
        name: "mealsAllTime",
        key: "vfdx0j42",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get mealsToday =>
      const ffai.ProjectStateFieldHandle(
        name: "mealsToday",
        key: "w9ltnki1",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get stories =>
      const ffai.ProjectStateFieldHandle(
        name: "stories",
        key: "85bp9bj1",
        typeName: "List<PostgresRow>",
      );
}

abstract final class TodayPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_go7ytkf6",
      type: "Scaffold",
      path: "TodayPage",
      name: "TodayPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_oyaz88wr",
            type: "Container",
            path: "TodayPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_9jm5sj61",
                type: "Column",
                path: "TodayPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_vxex9cwn",
                    type: "Text",
                    path: "TodayPage.body[0].children[0].children[0]",
                    name: "PromiseText",
                    text: "One tail. One meal. Every day.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_c08abnex",
                    type: "Text",
                    path: "TodayPage.body[0].children[0].children[1]",
                    name: "TodayLabel",
                    text: "Meals served today",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_1szd9c7q",
                    type: "Text",
                    path: "TodayPage.body[0].children[0].children[2]",
                    name: "MealsTodayText",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_l5ubgbic",
                    type: "Text",
                    path: "TodayPage.body[0].children[0].children[3]",
                    name: "AllTimeLabel",
                    text: "Since the first round",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_r05g8sga",
                    type: "Text",
                    path: "TodayPage.body[0].children[0].children[4]",
                    name: "MealsAllTimeText",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_h75xi57u",
                    type: "Button",
                    path: "TodayPage.body[0].children[0].children[5]",
                    name: "SupportButton",
                    text: "Support the truck",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_vaswjjxa",
                    type: "Text",
                    path: "TodayPage.body[0].children[0].children[6]",
                    name: "StoriesHeading",
                    text: "From the street",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_6t3c5h99",
                    type: "ListView",
                    path: "TodayPage.body[0].children[0].children[7]",
                    name: "ListView",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Card_0o73s2v6",
                        type: "Card",
                        path: "TodayPage.body[0].children[0].children[7].children[0]",
                        name: "Card",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_8vemqkot",
                            type: "Column",
                            path: "TodayPage.body[0].children[0].children[7].children[0].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_yz8hvxm3",
                                type: "Text",
                                path: "TodayPage.body[0].children[0].children[7].children[0].children[0].children[0]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_04wusm5a",
                                type: "Text",
                                path: "TodayPage.body[0].children[0].children[7].children[0].children[0].children[1]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_xxyhwq6o",
                                type: "Text",
                                path: "TodayPage.body[0].children[0].children[7].children[0].children[0].children[2]",
                                name: "Text",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_ikvt4ilc",
                    type: "Button",
                    path: "TodayPage.body[0].children[0].children[8]",
                    name: "AboutButton",
                    text: "Where the money goes",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

