// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

abstract final class ApiGroups {
  static const all = <String>[
  ];
}

abstract final class ActionBlocks {
  static const all = <String>[
  ];
}

abstract final class MockBackend {
  static const enabled = false;
  static const dataSource = "live";
}

abstract final class MockDatasets {
  static const all = <String>[
  ];
}

abstract final class MockCollectionBindings {
  static const all = <String, String>{
  };
}

abstract final class MockBindings {
  static const all = <String, String>{
  };
}

