// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class Components {
  static const all = <ffai.ProjectComponentHandle>[];
}
