// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'pages/about_page.dart' show aboutPageHandle;
import 'pages/today_page.dart' show todayPageHandle;

abstract final class Pages {
  static final aboutPage = aboutPageHandle;
  static final todayPage = todayPageHandle;
  static final all = <ffai.ProjectPageHandle>[
    aboutPage,
    todayPage,
  ];
}
