// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

abstract final class Project {
  static const id = "feeda-paw-hc0hpt";
  static const name = "Feed a Paw";
  static const sdkMetaVersion = 5;
}
