// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
// ignore_for_file: unnecessary_this

library;

import 'dart:collection' show MapBase;
import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class Enums {
  static const all = <ffai.EnumHandle>[];
}

abstract final class Structs {
  static const all = <ffai.StructHandle>[];
}

abstract final class Collections {
  static const all = <ffai.ProjectCollectionHandle>[];
}

abstract final class Tables {
  static final feedFund = ffai.ProjectTableHandle<FeedFundFields>(
    name: "feed_fund",
    description: "",
    isView: false,
    fields: FeedFundFields(),
  );
  static final feedStories = ffai.ProjectTableHandle<FeedStoriesFields>(
    name: "feed_stories",
    description: "",
    isView: false,
    fields: FeedStoriesFields(),
  );
  static final feedTotals = ffai.ProjectTableHandle<FeedTotalsFields>(
    name: "feed_totals",
    description: "",
    isView: false,
    fields: FeedTotalsFields(),
  );
  static final all = <ffai.ProjectTableHandle>[
    feedFund,
    feedStories,
    feedTotals,
  ];
}

final class FeedFundFields extends MapBase<String, ffai.PostgresTableField> {
  late final currency = ffai.ProjectTableFieldHandle(
    name: "currency",
    key: "j7vczzyh",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  late final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "cf0dxeon",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  late final name = ffai.ProjectTableFieldHandle(
    name: "name",
    key: "dosc0que",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  late final open = ffai.ProjectTableFieldHandle(
    name: "open",
    key: "iky09wlu",
    typeName: "Boolean",
    type: ffai.bool_,
    description: "",
    postgresType: "bool",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  late final raised = ffai.ProjectTableFieldHandle(
    name: "raised",
    key: "ha19o9o8",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  late final target = ffai.ProjectTableFieldHandle(
    name: "target",
    key: "j3fxe596",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "currency",
    "id",
    "name",
    "open",
    "raised",
    "target",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "currency" => this.currency,
    "id" => this.id,
    "name" => this.name,
    "open" => this.open,
    "raised" => this.raised,
    "target" => this.target,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class FeedStoriesFields extends MapBase<String, ffai.PostgresTableField> {
  late final area = ffai.ProjectTableFieldHandle(
    name: "area",
    key: "evrwlpbd",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  late final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "xtuo9gl8",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  late final photoPath = ffai.ProjectTableFieldHandle(
    name: "photo_path",
    key: "sofcg064",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  late final publishedAt = ffai.ProjectTableFieldHandle(
    name: "published_at",
    key: "xdyarkup",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  late final title = ffai.ProjectTableFieldHandle(
    name: "title",
    key: "cgn5yjrq",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  late final words = ffai.ProjectTableFieldHandle(
    name: "words",
    key: "3phtmj3a",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "area",
    "id",
    "photo_path",
    "published_at",
    "title",
    "words",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "area" => this.area,
    "id" => this.id,
    "photo_path" => this.photoPath,
    "published_at" => this.publishedAt,
    "title" => this.title,
    "words" => this.words,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class FeedTotalsFields extends MapBase<String, ffai.PostgresTableField> {
  late final kilosCollected = ffai.ProjectTableFieldHandle(
    name: "kilos_collected",
    key: "6bj0hj5s",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  late final mealsAllTime = ffai.ProjectTableFieldHandle(
    name: "meals_all_time",
    key: "2zbwyefr",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  late final mealsToday = ffai.ProjectTableFieldHandle(
    name: "meals_today",
    key: "08v6z9oz",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  late final mealsWeek = ffai.ProjectTableFieldHandle(
    name: "meals_week",
    key: "767cb6ec",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  late final runsDone = ffai.ProjectTableFieldHandle(
    name: "runs_done",
    key: "460t1jnz",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  late final spotsActive = ffai.ProjectTableFieldHandle(
    name: "spots_active",
    key: "d8go642o",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "kilos_collected",
    "meals_all_time",
    "meals_today",
    "meals_week",
    "runs_done",
    "spots_active",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "kilos_collected" => this.kilosCollected,
    "meals_all_time" => this.mealsAllTime,
    "meals_today" => this.mealsToday,
    "meals_week" => this.mealsWeek,
    "runs_done" => this.runsDone,
    "spots_active" => this.spotsActive,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

abstract final class CustomWidgets {
  static const all = <ffai.ProjectCustomWidgetHandle>[];
}

abstract final class CustomCode {
  static const functions = <String>[
  ];
  static const actions = <String>[
  ];
  static const widgets = <String>[
  ];
}

