// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

/// Existing Test Pilot groups + tests on this project, with their
/// real ids. To EDIT one in place (instead of creating a
/// duplicate), pass its id: app.testGroup(id: ...) /
/// app.qaTest(id: ...). Run/manage via the testpilot.* MCP tools
/// or `flutterflow ai test-pilot ...`.
abstract final class TestPilotTests {
  const TestPilotTests._();

  /// Every Test Pilot group on this project.
  static const groups = <({String id, String name, List<({String id, String name})> tests})>[
    (
      id: 'NZIPuD6S87dZdjXURrRQ',
      name: 'Feed-a-Paw core flows',
      tests: [
        (id: '85vvPr7lOUlgJCXgyiaT', name: 'The driver round opens for a signed-in person'),
        (id: 'JNLnhMIQ9HnSPrdU22P6', name: 'Anyone can look without an account'),
        (id: 'T7oovl7ghmBCjE1SrejG', name: 'Stories open'),
        (id: 'X6hIL4AFnFzwnaH5gbYa', name: 'Account tools work'),
        (id: 'nYXxRPyUXkxv5fsy4pBk', name: 'About says follow the truck, and asks for nothing'),
      ],
    ),
  ];
}
